AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*' #webpacker & rails 5.1
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'test/test_helper.rb'
    - 'vendor/bundle/**/*'

Lint/UselessAssignment:
  Exclude:
  - 'db/seeds.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'config/environments/*'
  - 'config/routes.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120 #default is 80
  Exclude:
  - 'db/seeds.rb'
  - 'app/controllers/items_controller.rb'
  - 'app/helpers/items_helper.rb'

Metrics/MethodLength:
  Exclude:
  - 'app/models/item.rb'
  - 'app/models/user.rb'
  - 'app/controllers/reminders_controller.rb'
  - 'app/controllers/items_controller.rb'
  - 'app/controllers/network_users_controller.rb'
  - 'app/helpers/items_helper.rb'

Metrics/ModuleLength:
  Exclude:
  - 'app/helpers/items_helper.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
