language: ruby
cache:
  bundler: true
  yarn: true
services:
  - redis-server
  - elasticsearch
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install google-chrome-stable
addons:
  postgresql: '9.6'
before_script:
  - sleep 10
  - psql -c 'create database dividi_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
  - bundle exec rspec
  - bundle exec rubocop
