meta_product_name: "Dividi"
meta_title: "Dividi - Awake your sleeping objects and manage them with your friends !"
meta_description: "Give back value to your objects and manage them with your community ! "
meta_image: "logo-noir.png"                       # should exist in `app/assets/images/`
twitter_account: "@dividi_twitter_account"   # required for Twitter Cards
