meta_product_name: "Dividi"
meta_title: "Dividi - Life is about sharing!"
meta_description: "Awake your sleeping objects and manage them with your friends ! "
meta_image: "logo-noir.png"                       # should exist in `app/assets/images/`
twitter_account: "@dividi_twitter_account"   # required for Twitter Cards
